spring:
  application:
    name: ownerMS
  cloud:
    # configuring Cloud Config
    consul:
      config:
        # true enables Cloud Config
        enabled: true
        # sets the base folder for configuration
        # config is the default name
        prefixes: config
        # sets the folder name used by all applications
        defaultContext: application
        # set the value of the separator
        # used to separate the profile name
        # in property sources with profiles
        profileSeparator: '::'
        format: YAML

# configure Resilience4j
resilience4j.circuitbreaker:
  instances:
    # name of service
    ownerMS:
      # threshold of failure % based on which the 
      # circuit breaker will move to the open state
      failure-rate-threshold: 50
      # minimum number of calls to make in closed state
      minimum-number-of-calls: 5
      # minimum number of call attempts in open state
      permitted-number-of-calls-in-half-open-state: 3
      # time circuit breaker should wait
      # before moving from open state to half open state
      wait-duration-in-open-state: 20s
      # allow to automatically move to half open state
      automatic-transition-from-open-to-half-open-enabled: true